package com.dell.convocation_iittp_2021;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.app.AppCompatDelegate;
import androidx.appcompat.widget.Toolbar;

import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.text.Html;
import android.text.style.BulletSpan;
import android.view.View;
import android.widget.TextView;

import java.util.Objects;

public class DirectorsReport extends AppCompatActivity {
        String s1 = "Chief Guest, Shri B. Santhanam, CEO, Saint-Gobain, Asia Pacific and India, Shri Amit Khare, Chairman, Board of Governors, IIT Tirupati; members of the Board of Governors; members of the Senate; graduands and their well-wishers; distinguished invitees; colleagues and students," +
                "\n In 2019, we conducted our first Convocation with the gracious presence of the then Hon'ble Minister of Education Shri Ramesh Pokhriyal ‘Nishank’ Ji as the chief guest and Hon'ble Dr. Audimulapu Suresh, Education Minister of Andhra Pradesh as the guest of honour. Due to the pervasive Covid crisis in 2020, we were considering whether to hold a virtual Convocation as many institutions had done. We decided to leave the decision to the students who were graduating, as it is their day - an occasion to celebrate the completion of their degree program. Overwhelmingly about 90% of the students opted for a physical Convocation, whenever it is possible to hold it. Today we are holding the joint 2nd and 3rd Convocation of the graduating students during 2020 and 2021." +
                "\n \n It gives me immense pleasure to welcome you all to the joint second and the third Convocation of the Indian Institute of Technology Tirupati. It is our privilege to have Shri B. Santhanam, an outstanding industry leader and IIT alumnus, address our graduating students today and award them the medals. On this occasion, we are proud to announce that a total of 209 B. Tech degrees, 98 M. Tech degrees, 9 M. Sc. degrees, 10 M. S. (by research) degrees, and the first PhD degree of the Institute will be awarded today." +
                "\n \n Since the inception of the Institute, we are engaged in recruiting world-class faculty members to teach and carry out cutting-edge research often in collaboration with industry and academic institutions of international repute. The Institute has appointed 109 faculty members against the sanctioned strength of 120 faculty positions. We strive to establish one of India’s leading environs for teaching, research and innovation at our Institute to attract top Indian and global companies to recruit our students and conduct collaborative research. The Institute is growing at a fast pace in terms of student and faculty strength, physical infrastructure creation, academic and research programmes to be one of the leading institutions in the country with its ideal of global outlook and local relevance." +
                "\n \n I, now, share with you some snapshots of our journey." ;
        String s2 = "The Institute commenced its operations with a total of 106 students in four B.Tech. programmes (Civil, Computer Science & Engineering, Electrical & Mechanical) in 2015. M.Tech programs in Computer Science, Electrical and Mechanical Engineering, and B.Tech in Chemical Engineering were launched in 2018. Gradually, the Institute expanded its strength and introduced a master’s programme in Mathematics & Statistics, and M. Tech in three streams of Civil Engineering in 2019. The Master’s programmes in Chemistry and Physics were launched in 2020." +
        "\n \n  The current student strength of about 1250 includes 823 B. Tech students, 134 M. Tech students, 84 M. Sc students, 41 MS and 168 PhD research students. It has been often pointed out that IITs have a skewed gender ratio. However, IIT Tirupati boasts of 21.87% girl students admitted to the B. Tech programmes and overall of 20.5 % girl students enrolled in various programmes at the Institute. Catering to the needs of economically marginal groups, the Institute offers scholarships for students hailing from low-income families. With the objective of working closely with the Indian armed forces, the Indian army has sponsored nine officers for the M.Tech programs in Electrical and Mechanical Engineering in 2020." ;
        String s3 = "Since March 2020, all academic and extra-mural activities have turned to be online. This crisis caused by Covid 19 did not give time even for the preparations to change the long-standing mode to a platform that was never expected to be the only mode for academic and other activities. But, within a week after the Institute advised all students to return home on March 16, 2020, due to the developing Covid pandemic situation, the Institute equipped itself to hold classes online for all its students. This unforeseen situation, certainly, caused a lot of trouble for those of the students who come from remotely located rural areas without much computing and network facilities. However, all faculty and students quickly adapted to the new normal. We managed to complete the 2019-20 academic requirements on time to enable graduating students to complete all their academic requirements by June 2020."
                + "\n \n We attempted to bring back students on campus in small batches starting from December 2020. However, with the start of the second wave of Covid-19 the students were advised to return home again in March 2021. The second wave impacted the Institute community quite hard with many employees and their family members and students being affected by Covid." +
                "\n\nStarting from June 2021, we have started bringing back students to campus in batches. Currently, all final year UG and PG students and research scholars are on campus." +
                "\n\nI am pleased to report here that the Institute joined hands with the nation in fighting the pandemic and remained at the forefront in finding solutions to combat and minimize the risks of the Covid 19 virus. A number of faculty, staff and students in the Institute dedicated their time and resources to find solutions to various problems that were faced by people due to this pandemic. Some of the major developments that IIT Tirupati made in dealing with the pandemic include:" +
                "\n\t●\t" +
                "Dr. Sunil Kumar developed a prototype of a thermal air sterilizer working with Opustayz Hospitality Solutions Pvt. Ltd, Bangalore/Trivandrum." +
                "\n\t●\t" +
                "A team comprising Dr. D.V. Kiran, Dr. Shihabudheen M. Maliyekkal, Prof. T.S. Natarajan, Dr. Ambrish Saxena, Prof. K.N. Satyanarayana, Dr. Ajay Kumar, and Dr. D. Subbareddy designed and developed N95 equivalent respirator, tying-up with M/s. Amara Raja Group for mass production of the respirators." +
                "\n\t●\t" +
                "Dr. Rama Krishna Gorthi, Dr. Subrahmanyam Gorthi, Mr. Gowtham, Mr. Vamshi, Mr. Arun, and Ms. Vaishnavi developed a deep learning-based approach for COVID Chest X-Ray image classification that classifies COVID samples with 100% recall and classifies normal, pneumonia and COVID samples with an overall accuracy of 96.3%." +
                "\n\t●\t" +
                "Dr. Sridhar Chimalakonda, Dheeraj Vagavolu and Akhila Sri Manasa Venigalla designed and developed an educational game called SurviveCovid-19 (https://survivecovid- 19.itch.io/game2020) that improves awareness of masks, sanitizers and social distancing in the theme of a city." +
                "\n\t●\t" +
                "A team consisting of Dr. Sridhar Chimalakonda and Noble Saji Mathews, developed a spam detection platform (https://stop-corona-iittp.herokuapp.com/) to flag textual/URL information as fake/misinformation message based on Machine Learning and Natural Language Processing." +
                "\n\t●\t" +
                "Dr. Sridhar Chimalakonda, Dheeraj Vagavolu and Akhila Sri Manasa Venigalla designed and developed an interactive web portal named Mood of India (https://moodofindia.herokuapp.com/) to gauge mood of India during Covid-19 based on analysis of over half a million tweets with hashtags of Corona by using machine learning and natural language processing. The portal has been used across India in states such as Rajasthan, Delhi, Punjab to understand the emotional state of people." +
                "\n\t●\t" +
                "A project coordinated by Dr. Kalidas Y and Dr. Krishna Prapoorna and supported by a team of about 20 students of the Institute, developed GeoCov19 algorithm to provide population mobility insights in and around containment zones or hot spots. The Director’s Report 12 GeoCov19 algorithm programmatically superimposes and synthesizes hot-spot information with mobility patterns to generate informative reports." +
                "\n\t●\t" +
                "A team comprising Dr. Reetesh Kumar Gangwar, Dr. Shihabudheen M M, Dr. Arijit Sharma from IIT Tirupati and Dr. Vasudharani Devanathan from IISER Tirupati developed a Portable Optical Cavity Sterilization Unit (POSCU) to provide efficient and rapid decontamination of personal protective equipment (PPE) and other household items. A working point-of-use sterilization unit has been developed with the support of the Science and Engineering Research Board (SERB), a statutory body under the Department of Science and Technology (DST)." +
                "\n\t●\t" +
                "A COVID-EMR app to help doctors to note the list of admitted patients and their conditions including O2 level, BP, PR and comorbidities, and to keep track of the record was developed by Institute's B. Tech students Mr. Sourabh Kumar and Mr. Surya Siriki, under the guidance of Dr. Panchatcharam Mariappan in consultation with SVIMS Hospital Tirupati." +
                "\n\t●\t" +
                "The team led by Dr. Ravi Shankar with the support of Institute staff designed and made over 2,000 face shields. These were distributed among various front line workers including health workers in hospitals, police, CISF airport personnel etc.";

        String s4 = "The infrastructural constraints of a new Institute and the ongoing pandemic did not dampen the spirit of our faculty members, and they have been rigorously involved in academic and sponsored research. The faculty members of the Institute have approximately 500 publications to their credit which include journal articles, book chapters and authored and edited books published by international publishers of repute. They have also presented approximately 700 research papers at national and international conferences." +
                "\n\nThe Institute has identified the following thrust areas to undertake inter-disciplinary research:" +
                "\n\nSmart Infrastructure; Food Technologies & Precision Agriculture; Materials & Manufacturing; Energy; Education Technologies; and Design. These have been identified taking into consideration the national needs, local relevance and global trends." +
                "\n\nDrawing on the strength of faculty expertise at IIT Tirupati and IISER Tirupati, a joint 'Center for Atomic, Molecular, Optical Sciences Technologies (CAMOST)’ was established. This was inaugurated on August 14, 2020 by Dr. Arbinda Mitra, Scientific Secretary in the o/o Principal Scientific Adviser to the Govt. of India. The Centre is envisioned to serve as a nodal hub for Director’s Report 13 several ongoing and upcoming scientific National Missions related to Interdisciplinary Cyber Physical Systems (ICPS), Artificial Intelligence (AI), Quantum Technology Applications (QTA), and the Supercomputing Mission (SCM)." +
                "\n\nFor a new Institute, it is a major achievement that we have been awarded the Technology Innovation Hub (TIH) in Positioning and Precision Technologies under the National Mission on Interdisciplinary Cyber Physical Systems. The Institute established a Section-8 company IIT Tirupati Navavishkar I-Hub Foundation for implementing the objectives of this mission including Technology Development; HRD & Skill Development; Innovation, Entrepreneurship and Start- up Ecosystem; and International Collaborations. The TIH will be receiving a funding of Rs. 100 crores over a period of five years." +
                "\n\nThe Institute takes pride in mentioning here that in the last two years our faculty members have successfully attracted funding for research and consultancy activities from the ministries of the Government as well as Industry. Our faculty members have been granted 82 sponsored research projects amounting to approximately 31.19 crores, and 84 industrial consultancy assignments amounting to around Rs. 7.5 crores. Some of the projects and consultancies are mentioned hereunder:" +
                "\n\t●\tDr. B. Krishna Prapoorna has been successful in attracting projects worth ₹ 12.97 crores and ₹ 68.34 lakh by the Ministry of Road Transport & Highways, and National Highways Authority of India on ‘National Facility for Accelerated Testing of Pavements and Vehicle Dynamics (NATPaVeD)’, and ‘Development of a Methodological Approach to Incorporate the Effect of Vehicle Type in IRC: 37-2018 Performance Prediction Models’ respectively." +
                "\n\t●\tProf. KSMS Raghavarao has been sanctioned with a project worth ₹ 2.60 crores under the PM Formalization of Micro Food Processing Enterprises Scheme from the Andhra Pradesh Food Processing Society. This project is sanctioned in the area of food technologies that the Institute has identified as one of its thrust areas." +
                "\n\t●\tProf. E. Anil Kumar has been granted two projects worth ₹ 1.44 crores and ₹ 1.24 crores on ‘Reversible Alkali-Metal based Hybrids for High Temperature Thermal Energy Storage” and “DST-IIT Bombay Energy Storage Platform on Hydrogen’ respectively by the Department of Science and Technology." +
                "\n\t●\tA project worth ₹ 59.53 lakh has been granted to Dr. Gouriprasanna Roy by the Science and Engineering Research Board- SERB on ‘Detoxification of Arsenic Compounds: Enzyme Mimetic Studies to Understand the Methylation of Arsenic by Ar(III) S- adenosylmethione (SAM) Methyltransferase (AS3MT)’." +
                "\n\t●\tDr. Shihabudheen M Maliyekkal received a sponsored research grant worth ₹ 52.37 lakh by the Department of Science and Technology to work on ‘Centre for Sustainable Treatment, Reuse and Management for Efficient, Affordable and Synergistic Solutions for Water (Water-IC for SUTRAM of EASY WATER)’." +
                "\n\t●\tA project worth ₹ 52.29 lakh was sanctioned to Dr. Mamilla Ravi Sankar by the Department of Science and Technology on ‘Abrasive Flow Finishing of Micro to Macro Complex Features’." +
                "\n\t●\tProf. Sasidhar Gumma has been entrusted with a research-based consultancy assignment worth ₹ 1.66 crores by Tata Advanced Systems Limited for Process design to manufacture medical oxygen plants." +
                "\n\t●\tAndhra Pradesh Pollution Control Board has sanctioned a research-based consultancy worth ₹ 1.06 crores to Prof. Suresh Jain to work on ‘Source Apportionment, Emission Inventory and carrying capacity studies for Vijayawada City’. Prof. Jain has also worked on another research-based consultancy sanctioned by the Board on ‘Development of Environment Plan 2021-2026 (A strategic development plan) for the State of Andhra Pradesh’. This consultancy was worth ₹ 45.6 lakh." +
                "\n\t●\tProf. K. N. Satyanarayana has been granted a CSR funded project by Godrej Projects Limited worth ₹ 41.25 lakh on ‘Lifecycle study of Construction waste at real estate Project sites.";

        String s5 = "Unperturbed by the restrictions in movement and the general constraints of the pandemic, our faculty, staff and students have maintained their academic consistency. They have received academic distinctions, honours and awards, and memberships on editorial boards of journals and prestigious international societies. Some of the awards are mentioned here:" +
                "Dr. Shihabudheen M. Maliyekkal received a Certificate of Appreciation from the Royal Society of Chemistry (RSC) as one of the top 5% of highly cited authors in RSC Journals, 2019." +
                "\n\t●\tDr. Gouri Prasanna Roy won the CRSI Bronze Medal 2020, Chemical Research Society of India (CRSI), February 2020." +
                "\n\t●\tDr. P. Gandeepan won the Research Excellence Award 2020, Institute of Scholars (InSc), Bengaluru, India, March 2020." +
                "\n\t●\tDr. Arijit Sharma won the prestigious Shastri Mobility Program (SMP) Award by the Shastri-Indo Canadian Institute (SICI) in April 2020 for a research visit to Dr. Amar Director’s Report 15 Vutha’s research group at the University of Toronto, Canada, pertaining to the project titled “Towards spectroscopy of molecular ions relevant to the interstellar medium”." +
                "\n\t●\tDr. Subrahmanyam Gorthi was chosen as the person of the week of the National Digital Library of India (NDLI) in June 2020." +
                "\n\t●\tDr. Krishna P. Biligiri was appointed as Associate Editor of the Resources, Conservation and Recycling Journal." ;

        String s6 = "Our faculty members have been proactive in organising seminars, conferences and workshops. The last two years diversified the range of the Institute’s academic activities. Following the pandemic restrictions, the activities were realigned to cater to the needs of teachers, practising engineers, and researchers. Some notable academic events that were organised by the Institute in the past two years include:" +
                "\n\t1. IIT Tirupati and Confederation of Indian Industry (CII) in association with Andhra Pradesh Food Processing Society, Department of Industries and Commerce, Government of Andhra Pradesh organised the fifth edition of FOODBIZ INDIA 2019 during October 16-17, 2019." +
                "\n\t2. The Department of Mathematics and Statistics organised an “Advanced Training School on Numerical PDEs and Inverse Problems (ATSNPDEIP-19)” in collaboration with the 'National Board for Higher Mathematics (NBHM)', Science and Engineering Research Board (SERB) and NUMA Engineering Services Ltd., Dundalk, Ireland, during December 9-20, 2019." +
                "\n\t3. Department of Humanities and Social Sciences in collaboration with the Office of The US Consulate General, Hyderabad, organised a three-day workshop on “Academic Writing” during December 10-12, 2019. The Department of Mechanical Engineering conducted an International Workshop on Materials for Energy Conversion and Storage during December 24-25, 2019. Around 120 participants attended the workshop from all over India." +
                "\n\t4. Department of Humanities and Social Sciences organised an international workshop on “Indian Conceptions of Multiculturalism” during January 8-9, 2020. A series of lectures were delivered covering the challenges of multiculturalism in a country like India. The experts arrived from all parts of the world to throw light on the multitude of languages, cultures and aspirations that constitute India and the aspects of unity in diversity that defines the Indian landscape." +
                "\n\t5. A one-day seminar on 'Spectroscopy and Imaging Technologies', jointly organised by the Department of Chemistry, IITT and PerkinElmer India Pvt. Ltd, was hosted at IIT Tirupati on February 1, 2020. The main aim of this seminar was to discuss the advances in spectroscopy and imaging technologies and their applications to a diverse field of chemical sciences, physics, biological sciences, pharmaceuticals, and engineering." +
                "\n\t6. The Department of Humanities and Social Sciences in collaboration with ICSSR-SRC, Hyderabad organised a three-day workshop on 'Academic Writing' during February 07- 09, 2020, at IIT Tirupati Campus." +
                "\n\t7. The Department of Mechanical Engineering organised a seminar on “multi-role multi- scale the mechanical test platforms” in collaboration with the 'Nanatom Technologies Pvt. Ltd' on February 18, 2020." +
                "\n\t8. The Department of Chemistry organised an Online conference on \"National Symposium on Recent Trends in Chemical Sciences\" (NSRTCS2020) during October 3-4, 2020." +
                "\n\t9. Dr. Krishna P. Biligiri, organised a session on “Sustainability & Resilience Aspects of Roadway Infrastructure”, in Vaishwik Bharatiya Vaigyanik (Vaibhav) summit (virtual), sponsored by the Government of India, in October 2020." +
                "\n\t10. The Geotechnical Engineering group of the Department of Civil and Environmental Engineering initiated a “Webinar Series in Geotechnical Investigations” to disseminate the state-of-the-art and state-of-the-practice in Geotechnical Investigations through a series of online lectures delivered by experts renowned globally. As a part of this series, a registration form of approx. 800 participants from over 40 countries across worldwide have been received." +
                "\n\t11. Advances in Atomic, Molecular, and Optical Sciences (AAMOS), an online international conference was held on a sliding timetable enabling global participation during December 14-18, 2020. It was organised jointly by the Centre for Atomic, Molecular, Optical Sciences Technologies (Joint Initiative of IIT Tirupati and IISER Tirupati) and Dayananda Sagar University, Bengaluru. The conference was convened by an international committee of distinguished scientists from Australia, Japan, India, Ireland, and the USA. 37 talks over five days were delivered at AAMOS '20 by leading experts from across the world." +
                "\n\t12. Dr. K. P. Naveen (IIT Tirupati) and Dr. Ashwin Ashok (Georgia State University) organised a workshop on “Last-mile Challenges and Standardisation Opportunities in Smart Infrastructure (LastMileS '21),” held in conjunction with the 13 International Conference on Communication Systems & Networks (COMSNETS '21), January 05, 2021." +
                "\n\t13. Statistical Mechanics in Chemistry and Biology (SMCB-2021) Conference was jointly organised by IIT Tirupati, IISER Tirupati, and IIT Goa over an online platform on January 23-25, 2021. The conference received overwhelming responses from the community. The community actively participated in talks and flash presentations, making it an atmosphere of conviviality. More than 300 participants registered for the conference across the country and a few from overseas as well." +
                "\n\t14. Department of Mechanical Engineering organised an international webinar during February 1-2, 2021 on the topic “Advances in Materials Processing and Mechanical Testing.”" +
                "\n\t15. An international conference on “Methodological Challenges in Assessing the Socio- economic Losses and Damages from Climate Change in India” was jointly organised by IIT Tirupati, Organisation for Economic Cooperation and Development (OECD), and National Institute of Disaster Management (NIDM), on May 25, 2021." +
                "\n\t16. IIT Tirupati hosted an International Conference on “Sustainable Pavement Technologies (icRS SPT 2021)”, sponsored by the international Resource Sustainability group during May 26-27, 2021.";

        String s7 = "IIT Tirupati inked a number of memorandums of understanding with educational institutions, government bodies as well as industry associates in the last two years." +
                "\n\nMoUs were signed with academic institutions like IIT Mandi, IISER Tirupati, Rajiv Gandhi University of Knowledge Technologies (RGUKT), Centre for Quantum Engineering Research and Education (CQuERE), a division of TCG Centres for Research and Education in Science and Technology, Central Food Technological Research Institute (CSIR-CFTRI) to establish a long-standing academic and scientific collaboration. These MoUs facilitate research and teaching visits, startup and incubation facilities, mutual support in postgraduate programmes as well as sharing of research facilities." +
                "\n\nThe Institute signed MoUs with government bodies like the National Highways Authority of India (NHAI), Andhra Pradesh Police, Petroleum Conservation Research Association (PCRA) to bridge the gap between industries and institutions, to enable internships for students, to acquaint faculty and students with the recent trends in the industry and to train police personnel on latest technologies." +
                "\n\nMoUs were also signed with the various industry associates. One such MoU was signed with ASN Fuels to develop technologies for the production of 2nd Generation Bioethanol with funding from Hindustan Petroleum." ;

        String s8 = "The Institute started its operations in 2015 from a temporary campus on the Tirupati-Renigunta Road. The Government of Andhra Pradesh has provided a picturesque 548 acres of land for the development of the permanent campus for the Institute."+
                "\n\nThe campus is being developed in multiple stages. A master plan has been prepared to build a campus to cater to 12,000 students while conserving its ecological features. It has been seen that in many institutions, that have been started in the last couple of decades, a few batches had graduated from temporary campuses. At IIT Tirupati we set ourselves a goal that the first batch should live at least one year in the permanent campus and achieved the target. The Stage 1A campus consisting of laboratories, hostels, classrooms and sports facilities was completed by 2018 by using prefab and sustainable technologies. Subsequently, the Stage 1B project consisting of a hostel building, a classroom complex building and an engineering unit building were completed by the end of 2019." +
                "\n\nCurrently, the Stage 1C project is under construction. In the academic zone, the buildings under construction include two Department Buildings that will have offices for about 100 faculty members and the associated laboratories, a Central Instrumentation Facility, a Lecture Hall Complex and Administrative Building. In the hostel zone, two hostels with 1,000 rooms, a Central Dining facility and sports facilities are under construction. In the residential zone, 168 apartments for faculty and staff, a 20 room guest house and Director's Bungalow are under construction. The external services for power, water, wastewater handling and roads are also under construction as part of this package. Two lakes over 10 acres are being created to store water." +
                "\n\nThe architects for the project include M/s Suresh Goel and Associates, Delhi and M/s ADPL, Delhi. The construction projects are being implemented through CPWD. The contractor for the Stage 1C project is M/s JMC Projects Ltd. The Third Party Quality Assurance is being provided by CUBE, IIT Madras. In spite of the challenges posed by the Covid-19 pandemic, the project team has been able to make significant progress. The contract for the Stage 1C project was awarded on March 20th, 2020. However, due to the nationwide lockdown, the contractor M/s JMC Projects was able to start mobilization only after Unlock 1.0 was announced during the Director’s Report 19 first week of June 2020. Viswakarma Awas, the workers' colony set up by the JMC Projects on a six acres plot in the campus is a model construction workers colony consisting of housing, RO water supply, STP for sewerage treatment, medical centre, children's school and gardens. The project has so far achieved over 5 million safe manhours. In recognition of the sustainable construction, health and safety practices adopted at the site, the projects have received many awards including the GRIHA Council Award for exemplary demonstration of Sustainable Building Materials/Technologies, HUDCO Award for sustainable construction, International Safety Award Merit 2021 from British Safety Council, RoSPA Gold Award 2020 from the Royal Society for the Prevention of Accidents, England, and the Trophy and Scroll for the category Construction Health, Safety & Environment presented at the 12th CIDC Viswakarma Awards 2021." +
                "\n\nIn the first year of operation in 2019, the campus was ranked sixth amongst the cleanest Higher Educational Institutions in the category of Residential Universities for the Swachh Campus Award." +
                "\n\nThe complete project team of the Institute Engineering team, Architects, CPWD and Contractor have been working tirelessly to create a world class campus to be benchmarked by other Institutions. I will be failing if I don't recognize the efforts of the nearly 2,000 migrant workers who are working under difficult conditions during the Covid-19 pandemic." ;
        String s9 = "Apart from their academic rigour, students at the Institute are active in the overall development of their personalities. Students engage with their peers in social service, club activities, cultural programmes, an annual festival, etc. Some of them include:"+
                "\n\nTirutsava: Techno-cultural Fest" +
                "\n\nTirutsava, the annual techno-cultural festival of IIT Tirupati organised by the students in February each year, is witness to a motley of cultural and technical events. Coding challenges, think tanks, debates, quizzes, and cultural activities give the students a chance to identify their creative and analytic sides. Since 2021 was a challenge due to the ongoing Covid pandemic, the student organisers conducted the festival entirely online. All the events including the concert and a stand-up comedy show were streamed online for the students to keep up their spirits in uncertain testing times." +
                "\n\n\nSPIC MACAY" +
                "\n\nSPIC MACAY chapter at IIT Tirupati has been very active, with the aim to promote Indian classical music and dance among the youth. In August 2019 IIT Tirupati hosted the Virasat series consisting of a number of art workshops and music performances by renowned artists. During the pandemic times, five classical concerts were organized online. These included flute recital by Sri Shashank Subramanyam, Qawalli programme by Warsi Brothers, violin recital concert by Padmashri A. Kanyakumari, Carnatic music recital by Dr. S. Sowmya, Vidushi Punya Srinivas gave a Veena recital, all of them accompanied by accomplished artists." +
                "\n\n\nNational Service Scheme (NSS) Activities" +
                "\n\nStudents of IIT Tirupati have been actively engaged in the activities of the National Service Scheme. Apart from their regular activities of NSS, the student volunteers launched an appreciation campaign ‘Gandhi Punyaha’ on October 2nd, 2020, for cleaning the campus giving a day of paid leave to the house-keeping staff. Kamalini was another campaign for self- production of sanitisers in the Institute to distribute it to the house-keeping staff, the residents of the adopted villages and to an orphanage. A scheme named ‘Mahatma’ was launched to support pilot projects by students to solve technological and real time problems. Activities like ‘No Plastic Week’, ‘Let’s Plant a Tree’, ‘Best out of Waste’, ‘Mind Maps, and Science Hack’ were the other initiatives of NSS at IITT." +
                "\n\nUnder the Unnat Bharat Abhiyan scheme, the Institute has adopted five villages close to the campus including Chindepalli, Jangalapalli, Rajulapalem, Pagali and Panguru. The activities undertaken by the students include household and village surveys; awareness programs on plastics and waste management; Swatch Bharath activities; awareness rallies; career development, motivational sessions and science experiments demonstration for school children." +
                "\n\n\nClubs and Sports Activities" +
                "\n\nIIT Tirupati has about 14 active clubs and societies under which they organise various extra- mural activities. With the increasing number of students, club activities became more diversified. Various clubs play a crucial role in getting the participants ready for Inter-IIT cultural, Director’s Report 21 technical and sports events. Under the Fit India Movement, the Institute launched its Fitness Club to organise yoga classes and informative webinars on the theme of the club. Sarathi, the Guidance and Counseling Unit is catered to the mental well-being of students by conducting counselling sessions, orientation programmes, yoga classes and life-skill sessions." +
                "\n\n\nPlacement" +
                "\n\nThe pandemic was a real challenge in terms of internship opportunities and placement drives. Despite the constraints, the Career Development Centre, IIT Tirupati, was instrumental in placing students in leading companies including pre-placement offers from top-notch organisations in different sectors like Information Technology, Core Engineering, Analytics, Consulting, etc. Some of the recruiters include Microsoft, Amazon, CommVault, iManage, Reliance Jio, Mentor Graphics, Mathworks, Versa Networks, iManage, Toshiba, TCS, L&T group, ITI limited, Alstom, AECOM etc. Many students went on for higher studies in leading institutions in India and abroad." +
                "\n\nRealigning to the current situation, Career Development Cell has successfully facilitated the virtual internship programme for the 2022 graduating batch. Many students chose to work in association with the Institute faculty in the design and development of technological innovations that help battle the recent Covid-19 crisis such as Air-Pollution Visualiser, SurviveCovid-19, COVID Chest X-Ray image classification, GeoCov19 algorithm, etc."
                ;

        String s10 = "Keeping up with the demands of the growing Institute and the current dynamic situation would not have been possible without the hard work, active support and cooperation of all our students, faculty, staff, agencies and industries sponsoring R&D projects." +
                "\n\nThe Institute is grateful to the Ministry of Education, Government of India, for its continued and sustained encouragement and support. The Ministers, officers and staff at MoE have always actively assisted and guided us. The liberal funding from the Govt. of India will enable us to set up the initial infrastructure to lay the foundation on which the Institute will continue to grow." +
                "\n\nI wish to avail this opportunity to place on record our sincere thanks to our mentor Institute IIT Madras which guided us since the inception and was always there to provide any required support." +
                "\n\nI also thank the Government of Andhra Pradesh for all the support it continues to extend in multiple ways." +
                "\n\nI wish to thank our former Chairman, Board of Governors Shri R. Subrahmanyam, and current Chairman Shri Amit Khare, and all Board members for their wise counsel, support and guidance, for enabling us to scale new heights." +
                "\n\nI would like to express my gratitude to our Chief Guest Shri B. Santhanam for gracing this Convocation. We are eager to hear his words of advice to our graduating students." +
                "\n\nBefore I end, I would like to congratulate the prize-winners and wish all our students of the second and the third batch happiness, professional success, and fulfilment from a life of service to their profession, family, country and society at large. You have been an extraordinary batch and set a benchmark for future batches with the way you have conducted yourselves with maturity, understanding the difficulties of a new institute in providing the necessary infrastructure and the current unprecedented pandemic situation. I see a great future for this Institute and assure you that you will be proud of your alma mater when you come back for your reunions." +
                "\n\nJai Hind!" ;

        TextView t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11;
        public void onCreate(@Nullable Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_directors_report);
            Objects.requireNonNull(getSupportActionBar()).hide();
            setTitle("Director's Report");
            t1 = findViewById(R.id.t1);
//            t2 = findViewById(R.id.t2);
            t3 = findViewById(R.id.academic_programs);
            t4 = findViewById(R.id.covid_crises);
            t5 = findViewById(R.id.sponsored_research);
            t6 = findViewById(R.id.distinctions);
            t7 = findViewById(R.id.conferences);
            t8 = findViewById(R.id.memorandums);
            t9 = findViewById(R.id.infrastructure);
            t10 = findViewById(R.id.extra);
            t11 = findViewById(R.id.acknowledgement);
            t1.setText(s1);
            t3.setText(s2);
            t4.setText(s3);
            t5.setText(s4);
            t6.setText(s5);
            t7.setText(s6);
            t8.setText(s7);
            t9.setText(s8);
            t10.setText(s9);
            t11.setText(s10);

            AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO);
//            t2.setOnClickListener(new View.OnClickListener() {
//                public void onClick(View v) {
//                    DirectorsReport.this.startActivity(new Intent("android.intent.action.VIEW", Uri.parse("https://drive.google.com/file/d/0BzTmJovVmlIUdk1zbmk5Z3UyWlhkOTRZNlZRYUVMcmg5VnVj/view?usp=sharing")));
//                }
//            });
        }

        public void left(View view) {
            finish();
        }
    }